id: P008101
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016924
  title: ལྷོ་ཁའི་ཆོས་འབྱུང་སྐྱེས་མའི་ནུ་རིན
  author: ''
  volumes:
    f36c8be0c432430ebd321194fd780e7f:
      image_group_id: I01JW229
      title: ''
      volume_number: 1
      total_pages: 390
ebook_metadata:
  title: ལྷོ་ཁའི་ཆོས་འབྱུང་སྐྱེས་མའི་ནུ་རིན
  author: ''
  sku: P008101
  cover: cover.jpg
  layers:
  - pagination
