id: opecha:P008101
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016924
  title: ལྷོ་ཁའི་ཆོས་འབྱུང་སྐྱེས་མའི་ནུ་རིན
  volume:
    10c85132d1044b208a7370ae34171ecc:
      image_group_id: I01JW229
      title: Volume 1 of lho kha'i chos 'byung skyes ma'i nu rin
      volume_number: 1
      total_pages: 390
  author: ''
ebook_metadata:
  title: ལྷོ་ཁའི་ཆོས་འབྱུང་སྐྱེས་མའི་ནུ་རིན
  author: ''
  sku: P008101
  cover: cover.jpg
  layers:
  - pagination
