id: P008101
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 13:01:37.138957
source_metadata:
  id: bdr:W00EGS1016924
  title: ལྷོ་ཁའི་ཆོས་འབྱུང་སྐྱེས་མའི་ནུ་རིན
  author: ''
  volumes:
    10c85132d1044b208a7370ae34171ecc:
      image_group_id: I01JW229
      title: Volume 1 of lho kha'i chos 'byung skyes ma'i nu rin
      volume_number: 1
      total_pages: 390
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
