id: IA9AAFB0C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T00:12:32+00:00'
last_modified: '2022-06-09T04:30:13.828456+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1016924
  title: ལྷོ་ཁའི་ཆོས་འབྱུང་སྐྱེས་མའི་ནུ་རིན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '5693':
      image_group_id: I01JW229
      title: Volume 1 of lho kha'i chos 'byung skyes ma'i nu rin
      total_pages: 390
      order: 1
      base_file: 5693.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
